kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-data
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.1Gi