version: '3.8'

services:
  web:
    build: ./app
    command: sh -c "python manage.py test && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin

volumes:
  postgres_data:
