{{- range .Values.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .label }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .label }}
  template:
    metadata:
      labels:
        app: {{ .label }}
    spec:
      containers:
      - name: {{ .containers.name }}
        image: {{ .containers.image }}
        resources:
          requests:
            memory: "100Mi" 
            cpu: "100m"      
          limits:
            memory: "200Mi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: {{ .name }}-config
        ports:
        - containerPort: {{ .containers.port }}
{{- end }}