apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secret.crt | b64enc | quote }}
  tls.key: {{ .Values.secret.key | b64enc | quote }}
