{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
spec:
  type: {{ .type }}
  selector:
    app: {{ .serviceSelector }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }} 
{{- end }}