{{- range .Values.statefulSet }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
data:
  {{- range $key, $value := .containers.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
