apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiture-api
  labels:
    app: voiture-api
spec:
  replicas: 1 # a changer a 3 
  selector:
    matchLabels:
      app: voiture-api
  template:
    metadata:
      labels:
        app: voiture-api
    spec:
      containers:
      - name: voiture-api-container
        image: ssdev1254/voiture:v3
        env:
        - name: RUNNING_CONTAINER
          value: "api"
        - name: POSTGRES_DB
          value: "voiture"
        - name: POSTGRES_USER
          value: "yahia"
        - name: POSTGRES_PASSWORD
          value: "yahia"
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_PORT
          value: "5432"
        - name: ALLOWED_HOST
          value: voiture-api-svc # django.aayyss.csc8567.luxbulb.org si on souhaite exposer l'api a l'exterieur
        - name: CSRF_TRUSTED_ORIGINS
          value: https://django.aayyss.csc8567.luxbulb.org
        ports:
        - containerPort: 8080
