namespace: u-9nl7s

ingress:
  host: "django.aayyss.csc8567.luxbulb.org"
  service: voiture-svc
  port: 8080


services: 
  - serviceName: voiture-api-svc
    serviceSelector: voiture-api
    port: 8080
    targetPort: 8080
    type: ClusterIP
  - serviceName: db
    serviceSelector: maDb
    port: 5432
    targetPort: 5432
    type: ClusterIP
  - serviceName: voiture-svc
    serviceSelector: voiture-dep
    port: 8080
    targetPort: 8080
    type: ClusterIP

deployment:
  - name: voiture-dep
    label: voiture-dep
    replicas: 1
    containers: 
      name: voiture-dep-container
      image: ssdev1254/voiture:v4
      port: 8080
      env:
        RUNNING_CONTAINER: "public"
        POSTGRES_DB: "voiture"
        POSTGRES_USER: "yahia"
        POSTGRES_PASSWORD: "yahia"
        DATABASE_HOST: "db"
        DATABASE_PORT: "5432"
        API_PORT: "8080"
        API_HOST: "http://voiture-api-svc:"
        ALLOWED_HOST: "django.aayyss.csc8567.luxbulb.org"
        CSRF_TRUSTED_ORIGINS: "https://django.aayyss.csc8567.luxbulb.org"

  - name: voiture-api
    label: voiture-api
    replicas: 1
    containers: 
      name: voiture-api-container
      image: ssdev1254/voiture:v4
      port: 8080
      env:
        RUNNING_CONTAINER: "api"
        POSTGRES_DB: "voiture"
        POSTGRES_USER: "yahia"
        POSTGRES_PASSWORD: "yahia"
        DATABASE_HOST: "db"
        DATABASE_PORT: "5432"
        ALLOWED_HOST: "voiture-api-svc" # django.aayyss.csc8567.luxbulb.org si on souhaite exposer l'api a l'exterieur
        CSRF_TRUSTED_ORIGINS: "https://django.aayyss.csc8567.luxbulb.org"

  - name: ma-db
    label: maDb
    replicas: 1
    containers: 
      name: my-container
      image: postgres:16
      port: 5432
      env:
        POSTGRES_DB: "voiture"
        POSTGRES_USER: "yahia"
        POSTGRES_PASSWORD: "yahia"
              

secret:
  name: secret
  crt: |
    -----BEGIN CERTIFICATE-----
    MIIDwDCCAqigAwIBAgIUAmSCwsyC4hgA3hBJDxRgq8c6EacwDQYJKoZIhvcNAQEL
    BQAwWDEqMCgGA1UEAwwhZGphbmdvLmFheXlzcy5jc2M4NTY3Lmx1eGJ1bGIub3Jn
    MSowKAYDVQQKDCFkamFuZ28uYWF5eXNzLmNzYzg1NjcubHV4YnVsYi5vcmcwHhcN
    MjQxMTExMDAzMDQxWhcNMjUxMTExMDAzMDQxWjBYMSowKAYDVQQDDCFkamFuZ28u
    YWF5eXNzLmNzYzg1NjcubHV4YnVsYi5vcmcxKjAoBgNVBAoMIWRqYW5nby5hYXl5
    c3MuY3NjODU2Ny5sdXhidWxiLm9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBAOUBIQHobCM4OjALYN7XJbfjY3yU5htxkSQ9cOyVqJlt162HeCMBbYxH
    xJC6qIUce9KSafpm0gxu6j+pQwNFnJb9dEEyu0zUHAHJsZdBSyd19kwzcgARs7vo
    fugpqKAJeglW2LV3v+S5XAvIfBD4AeaC5b7s0uqp3SNfP6qtHRGLzBuQ1z/mLvwQ
    TkncpE1fr8YVfwLkN2+sJl91owHAtiC7BvD855DZN5yeaqrv9aZhi8TvqBpc2KCJ
    j/ICpd/+hPUOYwlR3Y13IqT2gIiTLn1yAOImKNqvpeDaygotM9K5Yw+SlhZgcT+H
    0GcBHQuJNYb3FdN83tXvnF8jcu6WsTsCAwEAAaOBgTB/MB0GA1UdDgQWBBQpFRl4
    vT7W4k3O2xzvqODh0xec6jAfBgNVHSMEGDAWgBQpFRl4vT7W4k3O2xzvqODh0xec
    6jAPBgNVHRMBAf8EBTADAQH/MCwGA1UdEQQlMCOCIWRqYW5nby5hYXl5c3MuY3Nj
    ODU2Ny5sdXhidWxiLm9yZzANBgkqhkiG9w0BAQsFAAOCAQEAhBi+s6xEcSleAMfU
    UxVq8O0Hoqo0gCoE1p7ib+Sd4lUw2DocCNJw2rscSm6sEXLX6Jlws7s3MQP9dbIm
    Vmj2YvM3yNzZe91arw/bhZ5HO6hnh3eZJfo2Y/DSi2De7rz3K1ZB4M9pMf/5/DwM
    Yio7ORPYYMrClTX11C8EaVN8p2lBhCsGWpq3M1YkB4fzuTEm0fyg/D/IR5mmqOam
    a0TKCmiVrIjR6DgHzDHO9q2Ye3ujjsavWduvGYOHLlZqZbONrDh3DQOavhCw+iyn
    mxtiIzn6OZPeGkgNnmNm+N0knpW3SEwWvKt11tRiDLjHFE425rkw0iv/+G4bwnKp
    OozraQ==
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDlASEB6GwjODow
    C2De1yW342N8lOYbcZEkPXDslaiZbdeth3gjAW2MR8SQuqiFHHvSkmn6ZtIMbuo/
    qUMDRZyW/XRBMrtM1BwBybGXQUsndfZMM3IAEbO76H7oKaigCXoJVti1d7/kuVwL
    yHwQ+AHmguW+7NLqqd0jXz+qrR0Ri8wbkNc/5i78EE5J3KRNX6/GFX8C5DdvrCZf
    daMBwLYguwbw/OeQ2Tecnmqq7/WmYYvE76gaXNigiY/yAqXf/oT1DmMJUd2NdyKk
    9oCIky59cgDiJijar6Xg2soKLTPSuWMPkpYWYHE/h9BnAR0LiTWG9xXTfN7V75xf
    I3LulrE7AgMBAAECggEADhAOL1hO/7CtvhKMzdJncg3oJ5fbM5c7Qv705spf8qAQ
    rQrTIU8uo30qwHp968KuheVQ1bwnrPTItMUXpOVK8ui4kWJkpxilaaSxn6i2TUOM
    ruw/1WpA38qstGQOg1lhoZ4wK6Cha5HIab7Tg5U/RKEIK7vOTfPFbS0lszzzOob9
    7+vLDvZR/W5mFH0ibENEA7mcuvOQ9pv4sson6dZ5C6AjqOYMwxR80mwQNh1OIS5P
    5cfj2RWeZK06kefvqgYLRjjgOQQoxq70hZkmQuhiqYMEIV0VYhuoXYbjx/rdtMYN
    WV40VuaEVKpscXi2Gy8zg/wbp2G5I2WXv2yRFO8rKQKBgQDr/AeoGXAEdmzqRllk
    LobLlnnVrk3BL0ur8E2Atr8kbo6O3FKchsNl9UEylkngkRcUON6a03uB9xGY90/D
    ZZEF+h+0Ttw9YZYiT+XwSdVPJOFOBInSQIOZKKxCji/xDA9ZyXdLVzMEcvYmLgqq
    Wmt0qtKb9VYnMk5GG8dkkPaAqQKBgQD4bYoTdqZzDb1f8yaz9igJbjFOxuiWnjTS
    bC0lcS36AsGeBZunCyaWJukGtSsjxy5YoGdUxs2GemvEhxYk6/2mZtZ7dxqEWhO/
    0/TevJXjjQAqtxzhEeJb1ss+4aEb/yJAhkk8vu6geI4o0Fh3eCIxgIkhczK9CdZg
    +vuXMQz9QwKBgHhzJMlVaoqsk70keT4cTWse/ELn/AIODPbO6hA3tup2j8c1h+kj
    FBs3irayZTT9eaU1vdGS/miA3neQTCM09UfyujoDQoEGDWaoF3qFhR4neeSjhmFN
    0p3bV8mE382OVUuD/KL0+DJeJ2undoQrMMvU4Tj/iaDqGW/JgAXBxEA5AoGADRTf
    j3TRAP/5N+M654EPzKdTy10oBD5ic64klnMmQ6L/hQ2wi5RHvOJhpOvHUMP9Scdw
    iYNKcUljAV9HqDwRCEEkDC5SZCPGJHTJ0SzHC8tx9c3cpHFnpQRjgXUqIapGqHUp
    yBwZvrN6cOW/stLNoiOtlOhXBKNO+Z5dvzFjCLcCgYBTJuy6sUGkMFAsfdBvLe5N
    NzyahTIIrAOIWXyCBpwFzCkaWYlsVhsekfyDTVSgCo8wk5t3buCKXgn7v1kIRR/r
    B3GVBy8yKk/nsZuDQE+vgL/S7iZJ7J3EBnEoIBHfwi1UCt2Igxn9uqFWkonlPn4e
    mivmcYTMM6Xq2iSA0O601w==
    -----END PRIVATE KEY-----


  