namespace: u-9nl7s

ingress:
  host: "django.aayyss.csc8567.luxbulb.org"
  service: voiture-svc
  port: 8080

services: 
  - serviceName: voiture-api-svc
    serviceSelector: voiture-api
    port: 8080
    targetPort: 8080
    type: ClusterIP
  - serviceName: db
    serviceSelector: maDb
    port: 5432
    targetPort: 5432
    type: ClusterIP
  - serviceName: voiture-svc
    serviceSelector: voiture-dep
    port: 8080
    targetPort: 8080
    type: ClusterIP

deployment:
  - name: voiture-dep
    label: voiture-dep
    replicas: 1
    containers: 
      name: voiture-dep-container
      image: ssdev1254/voiture:v4
      port: 8080
      env:
        - name: RUNNING_CONTAINER
          value: "public"
        - name: POSTGRES_DB
          value: "voiture"
        - name: POSTGRES_USER
          value: "yahia"
        - name: POSTGRES_PASSWORD
          value: "yahia"
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_PORT
          value: "5432"
        - name: API_PORT
          value: "8080"
        - name: API_HOST
          value: "http://voiture-api-svc:"  # Note: changed from localhost
        - name: ALLOWED_HOST
          value: django.aayyss.csc8567.luxbulb.org
        - name: CSRF_TRUSTED_ORIGINS
          value: https://django.aayyss.csc8567.luxbulb.org
  - name: voiture-api
    label: voiture-api
    replicas: 1
    containers: 
      name: voiture-api-container
      image: ssdev1254/voiture:v4
      port: 8080
      env:
        - name: RUNNING_CONTAINER
          value: "api"
        - name: POSTGRES_DB
          value: "voiture"
        - name: POSTGRES_USER
          value: "yahia"
        - name: POSTGRES_PASSWORD
          value: "yahia"
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_PORT
          value: "5432"
        - name: ALLOWED_HOST
          value: voiture-api-svc # django.aayyss.csc8567.luxbulb.org si on souhaite exposer l'api a l'exterieur
        - name: CSRF_TRUSTED_ORIGINS
          value: https://django.aayyss.csc8567.luxbulb.org
  - name: ma-db
    label: maDb
    replicas: 1
    containers: 
      name: my-container
      image: postgres:16
      port: 5432
      env:
        - name: POSTGRES_DB
          value: "voiture"
        - name: POSTGRES_USER
          value: "yahia"
        - name: POSTGRES_PASSWORD
          value: "yahia"          
