---
# Source: djangohelm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: voiture-api-svc
spec:
  type: ClusterIP
  selector:
    app: voiture-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: djangohelm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: maDb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# Source: djangohelm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: voiture-svc
spec:
  type: ClusterIP
  selector:
    app: voiture-dep
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: djangohelm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiture-dep
  labels:
    app: voiture-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voiture-dep
  template:
    metadata:
      labels:
        app: voiture-dep
    spec:
      containers:
      - name: voiture-dep-container
        image: ssdev1254/voiture:v4
        resources:
          requests:
            memory: "100Mi" 
            cpu: "100m"      
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: RUNNING_CONTAINER 
          value: "public"
        - name: POSTGRES_DB 
          value: "voiture"
        - name: POSTGRES_USER 
          value: "yahia"
        - name: POSTGRES_PASSWORD 
          value: "yahia"
        - name: DATABASE_HOST 
          value: "db"
        - name: DATABASE_PORT 
          value: "5432"
        - name: API_PORT 
          value: "8080"
        - name: API_HOST 
          value: "http://voiture-api-svc:"
        - name: ALLOWED_HOST 
          value: "django.aayyss.csc8567.luxbulb.org"
        - name: CSRF_TRUSTED_ORIGINS 
          value: "https://django.aayyss.csc8567.luxbulb.org"
        ports:
        - containerPort: 8080
---
# Source: djangohelm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiture-api
  labels:
    app: voiture-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voiture-api
  template:
    metadata:
      labels:
        app: voiture-api
    spec:
      containers:
      - name: voiture-api-container
        image: ssdev1254/voiture:v4
        resources:
          requests:
            memory: "100Mi" 
            cpu: "100m"      
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: RUNNING_CONTAINER 
          value: "api"
        - name: POSTGRES_DB 
          value: "voiture"
        - name: POSTGRES_USER 
          value: "yahia"
        - name: POSTGRES_PASSWORD 
          value: "yahia"
        - name: DATABASE_HOST 
          value: "db"
        - name: DATABASE_PORT 
          value: "5432"
        - name: ALLOWED_HOST 
          value: "voiture-api-svc"
        - name: CSRF_TRUSTED_ORIGINS 
          value: "https://django.aayyss.csc8567.luxbulb.org"
        ports:
        - containerPort: 8080
---
# Source: djangohelm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ma-db
  labels:
    app: maDb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maDb
  template:
    metadata:
      labels:
        app: maDb
    spec:
      containers:
      - name: my-container
        image: postgres:16
        resources:
          requests:
            memory: "100Mi" 
            cpu: "100m"      
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: POSTGRES_DB 
          value: "voiture"
        - name: POSTGRES_USER 
          value: "yahia"
        - name: POSTGRES_PASSWORD 
          value: "yahia"
        ports:
        - containerPort: 5432
---
# Source: djangohelm/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: u-9nl7s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: django.aayyss.csc8567.luxbulb.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voiture-svc
                port:
                  number: 8080
  tls:
    - hosts:
        - django.aayyss.csc8567.luxbulb.org
      secretName: secret
---
# Source: djangohelm/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: kubernetes.io/tls
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR3RENDQXFpZ0F3SUJBZ0lVQW1TQ3dzeUM0aGdBM2hCSkR4UmdxOGM2RWFjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1dERXFNQ2dHQTFVRUF3d2haR3BoYm1kdkxtRmhlWGx6Y3k1amMyTTROVFkzTG14MWVHSjFiR0l1YjNKbgpNU293S0FZRFZRUUtEQ0ZrYW1GdVoyOHVZV0Y1ZVhOekxtTnpZemcxTmpjdWJIVjRZblZzWWk1dmNtY3dIaGNOCk1qUXhNVEV4TURBek1EUXhXaGNOTWpVeE1URXhNREF6TURReFdqQllNU293S0FZRFZRUUREQ0ZrYW1GdVoyOHUKWVdGNWVYTnpMbU56WXpnMU5qY3ViSFY0WW5Wc1lpNXZjbWN4S2pBb0JnTlZCQW9NSVdScVlXNW5ieTVoWVhsNQpjM011WTNOak9EVTJOeTVzZFhoaWRXeGlMbTl5WnpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU9VQklRSG9iQ000T2pBTFlON1hKYmZqWTN5VTVodHhrU1E5Y095VnFKbHQxNjJIZUNNQmJZeEgKeEpDNnFJVWNlOUtTYWZwbTBneHU2aitwUXdORm5KYjlkRUV5dTB6VUhBSEpzWmRCU3lkMTlrd3pjZ0FSczd2bwpmdWdwcUtBSmVnbFcyTFYzditTNVhBdklmQkQ0QWVhQzViN3MwdXFwM1NOZlA2cXRIUkdMekJ1UTF6L21MdndRClRrbmNwRTFmcjhZVmZ3TGtOMitzSmw5MW93SEF0aUM3QnZEODU1RFpONXllYXFydjlhWmhpOFR2cUJwYzJLQ0oKai9JQ3BkLytoUFVPWXdsUjNZMTNJcVQyZ0lpVExuMXlBT0ltS05xdnBlRGF5Z290TTlLNVl3K1NsaFpnY1QrSAowR2NCSFF1Sk5ZYjNGZE44M3RYdm5GOGpjdTZXc1RzQ0F3RUFBYU9CZ1RCL01CMEdBMVVkRGdRV0JCUXBGUmw0CnZUN1c0azNPMnh6dnFPRGgweGVjNmpBZkJnTlZIU01FR0RBV2dCUXBGUmw0dlQ3VzRrM08yeHp2cU9EaDB4ZWMKNmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUN3R0ExVWRFUVFsTUNPQ0lXUnFZVzVuYnk1aFlYbDVjM011WTNOagpPRFUyTnk1c2RYaGlkV3hpTG05eVp6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFoQmkrczZ4RWNTbGVBTWZVClV4VnE4TzBIb3FvMGdDb0UxcDdpYitTZDRsVXcyRG9jQ05KdzJyc2NTbTZzRVhMWDZKbHdzN3MzTVFQOWRiSW0KVm1qMll2TTN5TnpaZTkxYXJ3L2JoWjVITzZobmgzZVpKZm8yWS9EU2kyRGU3cnozSzFaQjRNOXBNZi81L0R3TQpZaW83T1JQWVlNckNsVFgxMUM4RWFWTjhwMmxCaENzR1dwcTNNMVlrQjRmenVURW0wZnlnL0QvSVI1bW1xT2FtCmEwVEtDbWlWcklqUjZEZ0h6REhPOXEyWWUzdWpqc2F2V2R1dkdZT0hMbFpxWmJPTnJEaDNEUU9hdmhDdytpeW4KbXh0aUl6bjZPWlBlR2tnTm5tTm0rTjBrbnBXM1NFd1d2S3QxMXRSaURMakhGRTQyNXJrdzBpdi8rRzRid25LcApPb3pyYVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  tls.key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRGxBU0VCNkd3ak9Eb3cKQzJEZTF5VzM0Mk44bE9ZYmNaRWtQWERzbGFpWmJkZXRoM2dqQVcyTVI4U1F1cWlGSEh2U2ttbjZadElNYnVvLwpxVU1EUlp5Vy9YUkJNcnRNMUJ3QnliR1hRVXNuZGZaTU0zSUFFYk83Nkg3b0thaWdDWG9KVnRpMWQ3L2t1VndMCnlId1ErQUhtZ3VXKzdOTHFxZDBqWHorcXJSMFJpOHdia05jLzVpNzhFRTVKM0tSTlg2L0dGWDhDNURkdnJDWmYKZGFNQndMWWd1d2J3L09lUTJUZWNubXFxNy9XbVlZdkU3NmdhWE5pZ2lZL3lBcVhmL29UMURtTUpVZDJOZHlLawo5b0NJa3k1OWNnRGlKaWphcjZYZzJzb0tMVFBTdVdNUGtwWVdZSEUvaDlCbkFSMExpVFdHOXhYVGZON1Y3NXhmCkkzTHVsckU3QWdNQkFBRUNnZ0VBRGhBT0wxaE8vN0N0dmhLTXpkSm5jZzNvSjVmYk01YzdRdjcwNXNwZjhxQVEKclFyVElVOHVvMzBxd0hwOTY4S3VoZVZRMWJ3bnJQVEl0TVVYcE9WSzh1aTRrV0prcHhpbGFhU3huNmkyVFVPTQpydXcvMVdwQTM4cXN0R1FPZzFsaG9aNHdLNkNoYTVISWFiN1RnNVUvUktFSUs3dk9UZlBGYlMwbHN6enpPb2I5CjcrdkxEdlpSL1c1bUZIMGliRU5FQTdtY3V2T1E5cHY0c3NvbjZkWjVDNkFqcU9ZTXd4UjgwbXdRTmgxT0lTNVAKNWNmajJSV2VaSzA2a2VmdnFnWUxSampnT1FRb3hxNzBoWmttUXVoaXFZTUVJVjBWWWh1b1hZYmp4L3JkdE1ZTgpXVjQwVnVhRVZLcHNjWGkyR3k4emcvd2JwMkc1STJXWHYyeVJGTzhyS1FLQmdRRHIvQWVvR1hBRWRtenFSbGxrCkxvYkxsbm5WcmszQkwwdXI4RTJBdHI4a2JvNk8zRktjaHNObDlVRXlsa25na1JjVU9ONmEwM3VCOXhHWTkwL0QKWlpFRitoKzBUdHc5WVpZaVQrWHdTZFZQSk9GT0JJblNRSU9aS0t4Q2ppL3hEQTlaeVhkTFZ6TUVjdlltTGdxcQpXbXQwcXRLYjlWWW5NazVHRzhka2tQYUFxUUtCZ1FENGJZb1RkcVp6RGIxZjh5YXo5aWdKYmpGT3h1aVdualRTCmJDMGxjUzM2QXNHZUJadW5DeWFXSnVrR3RTc2p4eTVZb0dkVXhzMkdlbXZFaHhZazYvMm1adFo3ZHhxRVdoTy8KMC9UZXZKWGpqUUFxdHh6aEVlSmIxc3MrNGFFYi95SkFoa2s4dnU2Z2VJNG8wRmgzZUNJeGdJa2hjeks5Q2RaZwordnVYTVF6OVF3S0JnSGh6Sk1sVmFvcXNrNzBrZVQ0Y1RXc2UvRUxuL0FJT0RQYk82aEEzdHVwMmo4YzFoK2tqCkZCczNpcmF5WlRUOWVhVTF2ZEdTL21pQTNuZVFUQ00wOVVmeXVqb0RRb0VHRFdhb0YzcUZoUjRuZWVTamhtRk4KMHAzYlY4bUUzODJPVlV1RC9LTDArREplSjJ1bmRvUXJNTXZVNFRqL2lhRHFHVy9KZ0FYQnhFQTVBb0dBRFJUZgpqM1RSQVAvNU4rTTY1NEVQektkVHkxMG9CRDVpYzY0a2xuTW1RNkwvaFEyd2k1Ukh2T0pocE92SFVNUDlTY2R3CmlZTktjVWxqQVY5SHFEd1JDRUVrREM1U1pDUEdKSFRKMFN6SEM4dHg5YzNjcEhGbnBRUmpnWFVxSWFwR3FIVXAKeUJ3WnZyTjZjT1cvc3RMTm9pT3RsT2hYQktOTytaNWR2ekZqQ0xjQ2dZQlRKdXk2c1VHa01GQXNmZEJ2TGU1TgpOenlhaFRJSXJBT0lXWHlDQnB3RnpDa2FXWWxzVmhzZWtmeURUVlNnQ284d2s1dDNidUNLWGduN3Yxa0lSUi9yCkIzR1ZCeTh5S2svbnNadURRRSt2Z0wvUzdpWko3SjNFQm5Fb0lCSGZ3aTFVQ3QySWd4bjl1cUZXa29ubFBuNGUKbWl2bWNZVE1NNlhxMmlTQTBPNjAxdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
---
# Source: djangohelm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: voiture-api-svc
spec:
  type: ClusterIP
  selector:
    app: voiture-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: djangohelm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: maDb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# Source: djangohelm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: voiture-svc
spec:
  type: ClusterIP
  selector:
    app: voiture-dep
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: djangohelm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiture-dep
  labels:
    app: voiture-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voiture-dep
  template:
    metadata:
      labels:
        app: voiture-dep
    spec:
      containers:
      - name: voiture-dep-container
        image: ssdev1254/voiture:v4
        resources:
          requests:
            memory: "100Mi" 
            cpu: "100m"      
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: RUNNING_CONTAINER 
          value: "public"
        - name: POSTGRES_DB 
          value: "voiture"
        - name: POSTGRES_USER 
          value: "yahia"
        - name: POSTGRES_PASSWORD 
          value: "yahia"
        - name: DATABASE_HOST 
          value: "db"
        - name: DATABASE_PORT 
          value: "5432"
        - name: API_PORT 
          value: "8080"
        - name: API_HOST 
          value: "http://voiture-api-svc:"
        - name: ALLOWED_HOST 
          value: "django.aayyss.csc8567.luxbulb.org"
        - name: CSRF_TRUSTED_ORIGINS 
          value: "https://django.aayyss.csc8567.luxbulb.org"
        ports:
        - containerPort: 8080
---
# Source: djangohelm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiture-api
  labels:
    app: voiture-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voiture-api
  template:
    metadata:
      labels:
        app: voiture-api
    spec:
      containers:
      - name: voiture-api-container
        image: ssdev1254/voiture:v4
        resources:
          requests:
            memory: "100Mi" 
            cpu: "100m"      
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: RUNNING_CONTAINER 
          value: "api"
        - name: POSTGRES_DB 
          value: "voiture"
        - name: POSTGRES_USER 
          value: "yahia"
        - name: POSTGRES_PASSWORD 
          value: "yahia"
        - name: DATABASE_HOST 
          value: "db"
        - name: DATABASE_PORT 
          value: "5432"
        - name: ALLOWED_HOST 
          value: "voiture-api-svc"
        - name: CSRF_TRUSTED_ORIGINS 
          value: "https://django.aayyss.csc8567.luxbulb.org"
        ports:
        - containerPort: 8080
---
# Source: djangohelm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ma-db
  labels:
    app: maDb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maDb
  template:
    metadata:
      labels:
        app: maDb
    spec:
      containers:
      - name: my-container
        image: postgres:16
        resources:
          requests:
            memory: "100Mi" 
            cpu: "100m"      
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: POSTGRES_DB 
          value: "voiture"
        - name: POSTGRES_USER 
          value: "yahia"
        - name: POSTGRES_PASSWORD 
          value: "yahia"
        ports:
        - containerPort: 5432
---
# Source: djangohelm/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: u-9nl7s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: django.aayyss.csc8567.luxbulb.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voiture-svc
                port:
                  number: 8080
  tls:
    - hosts:
        - django.aayyss.csc8567.luxbulb.org
      secretName: secret
