version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python voiture/manage.py collectstatic --noinput && \
            python voiture/manage.py migrate && \
            python voiture/manage.py createsuperuser \
              --email ${SUPERUSER_EMAIL} --username ${SUPERUSER_NAME} --noinput && \
            python voiture/manage.py shell < voiture/voiture/super.py
            python voiture/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

