apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiture-dep
  labels:
    app: voiture-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voiture-dep
  template:
    metadata:
      labels:
        app: voiture-dep
    spec:
      containers:
      - name: voiture-dep-container
        image: ssdev1254/voiture:v3
        env:
        - name: RUNNING_CONTAINER
          value: "public"
        - name: POSTGRES_DB
          value: "voiture"
        - name: POSTGRES_USER
          value: "yahia"
        - name: POSTGRES_PASSWORD
          value: "yahia"
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_PORT
          value: "5432"
        - name: API_PORT
          value: "8080"
        - name: API_HOST
          value: "http://voiture-api-svc:" # changement par rapport au ch3 ou c'etait localhost
        - name: ALLOWED_HOST
          value: django.aayyss.csc8567.luxbulb.org
        - name: CSRF_TRUSTED_ORIGINS
          value: https://django.aayyss.csc8567.luxbulb.org
        ports:
        - containerPort: 8080
