
FROM python:3.9-slim


WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY manage.py voiture api ./

ENV PYTHONUNBUFFERED=1


